create table if not exists public.brainbananas_comments (
    id bigint generated by default as identity primary key,
    session_code text not null,
    student_name text not null,
    author_role text not null default 'student',
    comment_text text not null,
    created_at timestamptz not null default now()
);

alter table public.brainbananas_comments
    add column if not exists author_role text not null default 'student';

create index if not exists brainbananas_comments_session_code_created_at_idx
    on public.brainbananas_comments (session_code, created_at);
